burp_probe/routes/auth.py
from flask import Blueprint, session, request, redirect, url_for, flash, render_template
from burp_probe.decorators import login_required
from burp_probe.models import User
from burp_probe.schemas import login_form_schema

blp = Blueprint('auth', __name__)

@blp.route('/login')
def login():
    if session.get('user_id'):
        return redirect(url_for('core.home'))
    return render_template('pages/login.html')

@blp.route('/login', methods=['POST'])
def login_submit():
    errors = login_form_schema.validate(request.form)
    if errors:
        return render_template(
            'pages/login.html',
            errors=errors,
        ), 400
    user = User.query.filter_by(email=request.form.get('email')).first()
    if user and user.check_password(request.form.get('password')):
        session['user_id'] = user.id
        return redirect(url_for('core.home'))
    flash('Invalid email or password.', category='error')
    return render_template('pages/login.html')

@blp.route('/logout')
@login_required
def logout():
    session.pop('user_id', None)
    session.clear()
    return redirect(url_for('core.index'))

burp_probe/routes/core.py
from flask import Blueprint, current_app, request, redirect, url_for, flash, render_template, abort
from burp_probe import db
from burp_probe.constants import ScanStates
from burp_probe.decorators import hx_trigger, login_required
from burp_probe.helpers import render_partial
from burp_probe.middleware import load_user, strip_empty_params, modify_response
from burp_probe.models import Node, Scan
from burp_probe.services.burp import BurpProApi, BurpScanBuilder, BurpServiceException, BurpIssueParser
from burp_probe.schemas import node_form_create_schema, node_form_update_schema, scan_form_schema
import json
import traceback

blp = Blueprint('core', __name__)

@blp.before_app_request
def call_request_middleware():
    load_user()
    strip_empty_params()

@blp.after_app_request
def call_response_middleware(response):
    response = modify_response(response)
    return response

@blp.route('/')
def index():
    return redirect(url_for('core.home'))

@blp.route('/home')
@login_required
def home():
    return redirect(url_for('core.scans'))

@blp.route('/logo')
def logo():
    return render_template(
        'pages/logo.html',
    )

# region assets

@blp.route('/assets')
@login_required
def assets():
    return render_template(
        'pages/assets.html',
        assets=Scan.get_assets(),
    )

@blp.route('/assets/table')
@login_required
def assets_table():
    return render_partial(
        'partials/tables/assets.html',
        assets=Scan.get_assets(),
    )

# endregion

# region nodes

@blp.route('/nodes')
@login_required
def nodes():
    return render_template(
        'pages/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/table')
@login_required
def nodes_table():
    return render_partial(
        'partials/tables/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/form')
@login_required
def nodes_form():
    form = {}
    if node_id := request.args.get('node_id'):
        if node := Node.query.get(node_id):
            form = node.serialize()
    return render_partial(
        'partials/forms/nodes.html',
        errors={},
        form=form,
    )

@blp.route('/nodes', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_create():
    errors = node_form_create_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node(
        name=request.form.get('name'),
        description=request.form.get('description'),
        protocol=request.form.get('protocol'),
        hostname=request.form.get('hostname'),
        port=request.form.get('port'),
        api_key=request.form.get('api_key'),
    )
    db.session.add(node)
    db.session.commit()
    flash('Node created.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['PATCH'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_update(node_id):
    request.form['id'] = node_id
    errors = node_form_update_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node.query.get(node_id)
    node.name=request.form.get('name')
    node.description=request.form.get('description')
    node.protocol=request.form.get('protocol')
    node.hostname=request.form.get('hostname')
    node.port=request.form.get('port')
    node.api_key=request.form.get('api_key')
    db.session.commit()
    flash('Node updated.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_delete(node_id):
    if not (node := Node.query.get(node_id)):
        abort(404, description='Node does not exist.')
    if node.scans:
        abort(409, description='Node has associated scans')
    db.session.delete(node)
    db.session.commit()
    flash('Node deleted.', 'success')
    return '', 200

@blp.route('/nodes/<string:node_id>/test')
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_test(node_id):
    node = Node.query.get(node_id)
    if node.is_alive:
        flash('Node is available.', 'success')
    else:
        flash('Node is not available.', 'warning')
    return '', 200

# endregion

# region scans

@blp.route('/scans')
@login_required
def scans():
    return render_template(
        'pages/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/table')
@login_required
def scans_table():
    return render_partial(
        'partials/tables/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/form')
@login_required
def scans_form():
    return render_partial(
        'partials/forms/scans.html',
        nodes=Node.get_live_nodes(),
        errors={},
        form={},
    )

@blp.route('/scans', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_create():
    errors = scan_form_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors=errors,
            form=request.form,
        ), 400
    name = request.form.get('name')
    description = request.form.get('description')
    credentials = request.form.get('credentials')
    configurations = request.form.get('configurations')
    scope_includes = request.form.get('scope_includes')
    scope_excludes = request.form.get('scope_excludes')
    target_urls = request.form.get('targets')
    node_id = request.form.get('node')
    node = Node.query.get(node_id)
    # build and run the scan
    scan = Scan(
        name=name,
        description=description,
        status='created',
        node=node,
    )
    db.session.add(scan)
    db.session.flush()
    callback_url = None
    scan_builder = BurpScanBuilder(callback_url, credentials, configurations, scope_includes, scope_excludes, target_urls)
    scan_config = scan_builder.config_as_json
    current_app.logger.debug(f"Scanner Config:\n{json.dumps(scan_config, indent=4)}")
    burp = BurpProApi(
        protocol=node.protocol,
        hostname=node.hostname,
        port=node.port,
        api_key=node.api_key,
    )
    try:
        response = burp.post_scan_config(scan_config)
    except BurpServiceException as e:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors={'_other': [str(e)]},
            form=request.form,
        ), 400
    scan.configuration = json.dumps(scan_config)
    scan.status = ScanStates.STARTED
    scan.task_id = response['task_id']
    db.session.commit()
    flash('Scan initialized.', 'success')
    return '', 201

# endregion

# region scan

@blp.route('/scans/<string:scan_id>')
@login_required
def scan(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_template(
        'pages/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>/header')
@login_required
def scan_header(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_partial(
        'partials/headers/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_delete(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    db.session.delete(scan)
    db.session.commit()
    flash('Scan deleted.', 'success')
    return '', 200

# endregion

# region issues

@blp.route('/scans/<string:scan_id>/issues/table')
@login_required
def issues_table(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    type_ids = [int(t) for t in request.args.get('type_ids', '').split(',') if t]
    return render_partial(
        'partials/tables/issues.html',
        scan=scan,
        type_ids=type_ids,
    )

# endregion

# region issue

@blp.route('/scans/<string:scan_id>/issues/<string:issue_id>')
@login_required
def issue(scan_id, issue_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    if not (issue_event := scan.get_issue_by_id(issue_id)):
        abort(404, description='Issue does not exist.')
    issue_event['parsed'] = BurpIssueParser(issue_event)
    return render_template(
        'pages/issue.html',
        issue_event=issue_event,
    )

# endregion

# region error handlers

from werkzeug.exceptions import HTTPException

@blp.app_errorhandler(HTTPException)
def error_handler(e):
    if 'HX-Request' in request.headers:
        message = e.description
        flash(message, 'error')
        return '', e.code
    else:
        return e

@blp.app_errorhandler(Exception)
def internal_server_error(e):
    if 'HX-Request' in request.headers:
        current_app.logger.error(traceback.format_exc())
        message = 'Internal server error.'
        flash(message, 'error')
        return '', 500
    else:
        return e

# endregion

burp_probe/templates/pages/assets.html
{% extends 'shared/page.html' %}
{% block content %}
<div class="flex items-center">
    <div class="flex-1 px-2 py-4"><h1 class="text-2xl font-medium">Assets</h1></div>
    <div class="flex-none"></div>
</div>
<div
    class="overflow-x-auto"
    hx-get="{{ url_for('core.assets_table') }}"
    hx-trigger="every 30s, watch-refresh-assets from:body"
    hx-swap="innerHTML"
>
{{ render_partial('partials/tables/assets.html', assets=assets) }}
</div>
{% endblock %}

burp_probe/templates/pages/issue.html
{% from 'shared/macros.html' import accordion, severity_svg %}
{% extends 'shared/page.html' %}
{% block content %}
<div class="flex items-center">
    <div class="flex-1 px-2 py-4"><h1 class="text-2xl font-medium">{{ issue_event.issue.name }}</h1></div>
    <div class="flex-none"></div>
</div>
<div class="my-4 p-4 flex flex-col md:flex-row justify-around rounded-lg bg-gray-100">
    <div class="basis-1/4 flex flex-col pr-0 md:pr-4 pb-4 md:pb-0 border-r-0 md:border-r border-b md:border-b-0 border-gray-300">
        <span class="pb-2 font-medium">Severity</span>
        <div class="flex items-center justify-start">
            <div class="pr-4">
                {{ severity_svg(issue_event.issue.severity, issue_event.issue.confidence, size=12) }}
            </div>
            <div class="flex flex-col items-start mr-4">
                <div>Severity:</div>
                <div>Confidence:</div>
            </div>
            <div class="flex flex-col items-start font-medium">
                <div>{{ issue_event.issue.severity|capitalize }}</div>
                <div>{{ issue_event.issue.confidence|capitalize }}</div>
            </div>
        </div>
    </div>
    <div class="basis-3/4 flex flex-col pt-4 md:pt-0 pl-0 md:pl-4">
        <span class="pb-2 font-medium">Location</span>
        <div class="flex items-center justify-start">
            <div class="flex flex-col items-start mr-4">
                <div>Host:</div>
                <div>Path:</div>
            </div>
            <div class="flex flex-col items-start font-medium">
                <div><code>{{ issue_event.issue.origin }}</code></div>
                <div><code>{{ issue_event.issue.path }}</code></div>
            </div>
        </div>
    </div>
</div>
<div class="flex flex-col gap-4">
    {{ accordion('Description', issue_event.issue.description, 'description')}}
    {{ accordion('Background', issue_event.issue.issue_background, 'background')}}
    {{ accordion('Remediation', issue_event.issue.remediation_background, 'remediation')}}
    {% for exhibit in issue_event.parsed.exhibits %}
    {% set id = exhibit.title|lower + '-' + loop.index|string %}
    {{ accordion(exhibit.title, exhibit.content, id, loop.index)}}
    {% endfor %}
</div>
<style>
/* Issue accordion functionality */
.bp-accordion-trigger {
    position: absolute;
    opacity: 0;
    z-index: -1;
}
.bp-accordion-content {
    max-height: 0;
    overflow: hidden;
    transition: all 0.5s;
}
.bp-accordion-trigger:checked ~ .bp-accordion-content {
    max-height: 100rem;
    overflow-y: scroll;
}
/* Accordion arrow animation */
.bp-accordion-label svg {
    transform: rotate(0deg);
    transition: all 0.5s;
}
.bp-accordion-trigger:checked + .bp-accordion-label svg {
    transform: rotate(90deg);
}
/* Issue content where Tailwind is unavailable */
.bp-issue-content {
    padding: 0 !important;
    div {
        padding: 1rem;
        border-top-width: 1px;
        /* add margin to everything for spacing */
        /* can't use flex+gap because of `<b>`, etc. */
        > *:not(:last-child) {
            margin-bottom: 1.5rem;
        }
    }
    ul { 
        list-style-type: disc; 
        list-style-position: inside; 
    }
    ol { 
        list-style-type: decimal; 
        list-style-position: inside; 
    }
}
</style>
{% endblock %}

burp_probe/templates/pages/login.html
{% extends 'shared/layout.html' %}
{% block body %}
<section>
    <div class="flex flex-col items-center bg-base-200 px-6 py-8 mx-auto h-screen">
        <div class="flex flex-col items-center md:max-w-md p-8 space-y-6 bg-base-100 rounded-lg shadow-lg">
            <img src="{{ url_for('static', filename='images/logo.png') }}" />
            <div class="w-full">
                <h1 class="text-2xl font-medium">
                    Sign in to your account
                </h1>
                <form
                    class="flex flex-col space-y-4"
                    action="{{ url_for('auth.login_submit') }}"
                    method="post"
                >
                    <div class="flex flex-col">
                        <div class="label">
                            <span class="label-text">Email Address</span>
                            {% if 'email' in errors %}
                            <span class="ml-4 text-xs text-red-500">{{ errors['email']|first }}</span>
                            {% endif %}
                        </div>
                        <input 
                            name="email"
                            type="text"
                            placeholder="name@domain.com"
                            class="input input-bordered"
                        />
                    </div>
                    <div class="flex flex-col">
                        <div class="label">
                            <span class="label-text">Password</span>
                            {% if 'password' in errors %}
                            <span class="ml-4 text-xs text-red-500">{{ errors['password']|first }}</span>
                            {% endif %}
                        </div>
                        <input 
                            name="password"
                            type="password"
                            placeholder="••••••••••"
                            class="input input-bordered"
                        />
                    </div>
                    <div class="flex flex-row-reverse justify-between mt-9">
                        <button id="save" class="btn">Submit</button>
                        {% if '_other' in errors %}
                        <div class="mt-4 ml-4 text-xs text-red-500">{{ errors['_other']|first }}</div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

burp_probe/templates/pages/logo.html
{% extends 'shared/layout.html' %}
{% block body %}
<div class="flex flex-col items-center justify-center bg-base-100 mx-auto h-screen">
    <div class="flex mb-6">
        <div class="flex flex-col items-center justify-center">
            <div class="mr-2 mt-1.5" style="background-color: #00b5ef;">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-40 h-40 -rotate-45">
                    <g fill="none" stroke-width="1.5" stroke="white" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M16.95 9.01c3.02.739 5.05 2.123 5.05 3.714C22 15.091 17.52 17 12 17S2 15.091 2 12.724C2 11.134 4.04 9.739 7.07 9"/>
                        <path d="M7 9c0 1.105 2.239 2 5 2s5-.895 5-2v-.035C17 6.223 14.761 4 12 4S7 6.223 7 8.965V9m8 8l2 3m-8.5-3L7 20m5-6h.01M7 13h.01M17 13h.01"/>
                    </g>
                </svg>
            </div>
        </div>
        <div class="flex flex-col tracking-tight">
            <div class="text-9xl font-medium">Burp Probe</div>
            <div class="text-6xl font-thin ml-1" style="color: #00b5ef;">Remote Scan Manager</div>
        </div>
    </div>
</div>
{% endblock %}

burp_probe/templates/pages/nodes.html
{% extends 'shared/page.html' %}
{% block content %}
<div class="flex items-center">
    <div class="flex-1 px-2 py-4"><h1 class="text-2xl font-medium">Nodes</h1></div>
    <div class="flex-none">
        <button
            class="btn btn-circle btn-ghost"
            hx-get="{{ url_for('core.nodes_form') }}"
            hx-target="#form_container"
        >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>              
        </button>
    </div>
</div>
<div
    class="overflow-x-auto"
    hx-get="{{ url_for('core.nodes_table') }}"
    hx-trigger="every 30s, watch-refresh-nodes from:body"
    hx-swap="innerHTML"
>
{{ render_partial('partials/tables/nodes.html', nodes=nodes) }}
</div>
<dialog id="modal" class="modal">
    <div class="modal-box">
        <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
        </form>
        <div
            id="form_container"
            class="p-2"
            hx-on:htmx:before-swap="if(event.detail.xhr.status==201){modal.close();}"
            hx-on:htmx:after-swap="modal.showModal()"
        ></div>
    </div>
</dialog>
{% endblock %}

burp_probe/templates/pages/scan.html
{% extends 'shared/page.html' %}
{% block content %}
<div class="flex items-center">
    <div class="flex-1 px-2 py-4"><h1 class="text-2xl font-medium">{{ scan.name }}</h1></div>
    <div class="flex-none">
        <button class="btn btn-circle btn-ghost" onclick="document.getElementById('showConfigModal').showModal()">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 0 1 1.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.559.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.894.149c-.424.07-.764.383-.929.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 0 1-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.398.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 0 1-.12-1.45l.527-.737c.25-.35.272-.806.108-1.204-.165-.397-.506-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.108-1.204l-.526-.738a1.125 1.125 0 0 1 .12-1.45l.773-.773a1.125 1.125 0 0 1 1.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894Z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
            </svg>
        </button>
    </div>
</div>
<div
    hx-get="{{ url_for('core.scan_header', scan_id=scan.id) }}"
    hx-trigger="every 30s"
    hx-swap="innerHTML"
>
{{ render_partial('partials/headers/scan.html', scan=scan) }}
</div>
<div
    class="overflow-auto"
    hx-get="{{ url_for('core.issues_table', scan_id=scan.id) }}"
    hx-trigger="every 30s"
    hx-swap="innerHTML"
    hx-vals='js:{"type_ids": getExpandedTypeIds()}'
>
{{ render_partial('partials/tables/issues.html', scan=scan, type_ids=[]) }}
</div>
<dialog id="showConfigModal" class="modal">
    <div class="modal-box">
        <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
        </form>
        <div class="flex flex-col text-sm">
            <h1 class="text-2xl font-medium px-2 py-4">JSON Configuration</h1>
            <div class="overflow-x-auto">
                <pre><code>{{ scan.parsed.config|ppjson }}</code></pre>
            </div>
        </div>
    </div>
</dialog>
<style>
/* Table arrow animation */
.bp-arrow-closed {
    transform: rotate(0deg);
    transition: all 0.5s;
}
.bp-arrow-opened {
    transform: rotate(90deg);
}
/* Table rows initial accordion state */
.bp-collapsed {
    visibility: collapse;
}
</style>
<script>
function toggleCollapse(type_id) {
    document.querySelectorAll(`svg[data-type="${type_id}"]`).forEach((element) => {
        element.classList.toggle("bp-arrow-opened");
    });
    document.querySelectorAll(`tr[data-type="${type_id}"]`).forEach((element) => {
        element.classList.toggle("bp-collapsed");
    });
}

function getExpandedTypeIds() {
    return [...document.querySelectorAll("svg.bp-arrow-opened")].map((element) => {
        return element.dataset.type;
    }).join(",");
}
</script>
{% endblock %}

burp_probe/templates/pages/scans.html
{% extends 'shared/page.html' %}
{% block content %}
<div class="flex items-center">
    <div class="flex-1 px-2 py-4"><h1 class="text-2xl font-medium">Scans</h1></div>
    <div class="flex-none">
        <button
            class="btn btn-circle btn-ghost"
            hx-get="{{ url_for('core.scans_form') }}"
            hx-target="#form_container"
        >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>              
        </button>
    </div>
</div>
<div
    class="overflow-x-auto"
    hx-get="{{ url_for('core.scans_table') }}"
    hx-trigger="every 30s, watch-refresh-scans from:body"
    hx-swap="innerHTML"
>
{{ render_partial('partials/tables/scans.html', scans=scans) }}
</div>
<dialog id="modal" class="modal">
    <div class="modal-box">
        <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
        </form>
        <div
            id="form_container"
            class="p-2"
            hx-on:htmx:before-swap="if(event.detail.xhr.status==201){modal.close();}"
            hx-on:htmx:after-swap="modal.showModal()"
        ></div>
    </div>
</dialog>
{% endblock %}