burp_probe/routes/core.py
from flask import Blueprint, current_app, request, redirect, url_for, flash, render_template, abort
from burp_probe import db
from burp_probe.constants import ScanStates
from burp_probe.decorators import hx_trigger, login_required
from burp_probe.helpers import render_partial
from burp_probe.middleware import load_user, strip_empty_params, modify_response
from burp_probe.models import Node, Scan
from burp_probe.services.burp import BurpProApi, BurpScanBuilder, BurpServiceException, BurpIssueParser
from burp_probe.schemas import node_form_create_schema, node_form_update_schema, scan_form_schema
import json
import traceback

blp = Blueprint('core', __name__)

@blp.before_app_request
def call_request_middleware():
    load_user()
    strip_empty_params()

@blp.after_app_request
def call_response_middleware(response):
    response = modify_response(response)
    return response

@blp.route('/')
def index():
    return redirect(url_for('core.home'))

@blp.route('/home')
@login_required
def home():
    return redirect(url_for('core.scans'))

@blp.route('/logo')
def logo():
    return render_template(
        'pages/logo.html',
    )

# region assets

@blp.route('/assets')
@login_required
def assets():
    return render_template(
        'pages/assets.html',
        assets=Scan.get_assets(),
    )

@blp.route('/assets/table')
@login_required
def assets_table():
    return render_partial(
        'partials/tables/assets.html',
        assets=Scan.get_assets(),
    )

# endregion

# region nodes

@blp.route('/nodes')
@login_required
def nodes():
    return render_template(
        'pages/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/table')
@login_required
def nodes_table():
    return render_partial(
        'partials/tables/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/form')
@login_required
def nodes_form():
    form = {}
    if node_id := request.args.get('node_id'):
        if node := Node.query.get(node_id):
            form = node.serialize()
    return render_partial(
        'partials/forms/nodes.html',
        errors={},
        form=form,
    )

@blp.route('/nodes', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_create():
    errors = node_form_create_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node(
        name=request.form.get('name'),
        description=request.form.get('description'),
        protocol=request.form.get('protocol'),
        hostname=request.form.get('hostname'),
        port=request.form.get('port'),
        api_key=request.form.get('api_key'),
    )
    db.session.add(node)
    db.session.commit()
    flash('Node created.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['PATCH'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_update(node_id):
    request.form['id'] = node_id
    errors = node_form_update_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node.query.get(node_id)
    node.name=request.form.get('name')
    node.description=request.form.get('description')
    node.protocol=request.form.get('protocol')
    node.hostname=request.form.get('hostname')
    node.port=request.form.get('port')
    node.api_key=request.form.get('api_key')
    db.session.commit()
    flash('Node updated.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_delete(node_id):
    if not (node := Node.query.get(node_id)):
        abort(404, description='Node does not exist.')
    if node.scans:
        abort(409, description='Node has associated scans')
    db.session.delete(node)
    db.session.commit()
    flash('Node deleted.', 'success')
    return '', 200

@blp.route('/nodes/<string:node_id>/test')
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_test(node_id):
    node = Node.query.get(node_id)
    if node.is_alive:
        flash('Node is available.', 'success')
    else:
        flash('Node is not available.', 'warning')
    return '', 200

# endregion

# region scans

@blp.route('/scans')
@login_required
def scans():
    return render_template(
        'pages/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/table')
@login_required
def scans_table():
    return render_partial(
        'partials/tables/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/form')
@login_required
def scans_form():
    return render_partial(
        'partials/forms/scans.html',
        nodes=Node.get_live_nodes(),
        errors={},
        form={},
    )

@blp.route('/scans', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_create():
    errors = scan_form_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors=errors,
            form=request.form,
        ), 400
    name = request.form.get('name')
    description = request.form.get('description')
    credentials = request.form.get('credentials')
    configurations = request.form.get('configurations')
    scope_includes = request.form.get('scope_includes')
    scope_excludes = request.form.get('scope_excludes')
    target_urls = request.form.get('targets')
    node_id = request.form.get('node')
    node = Node.query.get(node_id)
    # build and run the scan
    scan = Scan(
        name=name,
        description=description,
        status='created',
        node=node,
    )
    db.session.add(scan)
    db.session.flush()
    callback_url = None
    scan_builder = BurpScanBuilder(callback_url, credentials, configurations, scope_includes, scope_excludes, target_urls)
    scan_config = scan_builder.config_as_json
    current_app.logger.debug(f"Scanner Config:\n{json.dumps(scan_config, indent=4)}")
    burp = BurpProApi(
        protocol=node.protocol,
        hostname=node.hostname,
        port=node.port,
        api_key=node.api_key,
    )
    try:
        response = burp.post_scan_config(scan_config)
    except BurpServiceException as e:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors={'_other': [str(e)]},
            form=request.form,
        ), 400
    scan.configuration = json.dumps(scan_config)
    scan.status = ScanStates.STARTED
    scan.task_id = response['task_id']
    db.session.commit()
    flash('Scan initialized.', 'success')
    return '', 201

# endregion

# region scan

@blp.route('/scans/<string:scan_id>')
@login_required
def scan(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_template(
        'pages/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>/header')
@login_required
def scan_header(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_partial(
        'partials/headers/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_delete(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    db.session.delete(scan)
    db.session.commit()
    flash('Scan deleted.', 'success')
    return '', 200

# endregion

# region issues

@blp.route('/scans/<string:scan_id>/issues/table')
@login_required
def issues_table(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    type_ids = [int(t) for t in request.args.get('type_ids', '').split(',') if t]
    return render_partial(
        'partials/tables/issues.html',
        scan=scan,
        type_ids=type_ids,
    )

# endregion

# region issue

@blp.route('/scans/<string:scan_id>/issues/<string:issue_id>')
@login_required
def issue(scan_id, issue_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    if not (issue_event := scan.get_issue_by_id(issue_id)):
        abort(404, description='Issue does not exist.')
    issue_event['parsed'] = BurpIssueParser(issue_event)
    return render_template(
        'pages/issue.html',
        issue_event=issue_event,
    )

# endregion

# region error handlers

from werkzeug.exceptions import HTTPException

@blp.app_errorhandler(HTTPException)
def error_handler(e):
    if 'HX-Request' in request.headers:
        message = e.description
        flash(message, 'error')
        return '', e.code
    else:
        return e

@blp.app_errorhandler(Exception)
def internal_server_error(e):
    if 'HX-Request' in request.headers:
        current_app.logger.error(traceback.format_exc())
        message = 'Internal server error.'
        flash(message, 'error')
        return '', 500
    else:
        return e

# endregion

burp_probe/templates/partials/forms/nodes.html
<form
    class="flex flex-col space-y-4"
    {% if 'id' in form %}
    hx-patch="{{ url_for('core.nodes_update', node_id=form.id) }}"
    {% else %}
    hx-post="{{ url_for('core.nodes_create') }}"
    {% endif %}
    hx-swap="outerHTML"
>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Name *</span>
            {% if 'name' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['name']|first }}</span>
            {% endif %}
        </div>
        <input
            name="name"
            type="text"
            placeholder="My First Node"
            class="input input-bordered"
            {% if 'name' in form %}
            value="{{ form.name }}"
            {% endif %}
        />
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Description</span>
            {% if 'description' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['description']|first }}</span>
            {% endif %}
        </div>
        <input
            name="description"
            type="text"
            placeholder="The first node I ever created."
            class="input input-bordered"
            {% if 'description' in form %}
            value="{{ form.description }}"
            {% endif %}
        />
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Protocol *</span>
            {% if 'protocol' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['protocol']|first }}</span>
            {% endif %}
        </div>
        <input
            name="protocol"
            type="text"
            placeholder="http or https"
            class="input input-bordered"
            {% if 'protocol' in form %}
            value="{{ form.protocol }}"
            {% endif %}
        />
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Hostname/IP *</span>
            {% if 'hostname' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['hostname']|first }}</span>
            {% endif %}
        </div>
        <input
            name="hostname"
            type="text"
            placeholder="hostname or IP address"
            class="input input-bordered"
            {% if 'hostname' in form %}
            value="{{ form.hostname }}"
            {% endif %}
        />
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Port *</span>
            {% if 'port' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['port']|first }}</span>
            {% endif %}
        </div>
        <input
            name="port"
            type="text"
            placeholder="1337"
            class="input input-bordered"
            {% if 'port' in form %}
            value="{{ form.port }}"
            {% endif %}
        />
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">API Key *</span>
            {% if 'api_key' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['api_key']|first }}</span>
            {% endif %}
        </div>
        <input
            name="api_key"
            type="text"
            placeholder="created by Burp Suite Pro"
            class="input input-bordered"
            {% if 'api_key' in form %}
            value="{{ form.api_key }}"
            {% endif %}
        />
    </div>
        <div class="flex flex-row-reverse justify-between mt-9">
        <button id="save" class="btn">Save</button>
        {% if '_other' in errors %}
        <div class="mt-4 ml-4 text-xs text-red-500">{{ errors['_other']|first }}</div>
        {% endif %}
    </div>
</form>

burp_probe/templates/partials/forms/scans.html
<form
    class="flex flex-col space-y-4"
    hx-post="{{ url_for('core.scans_create') }}"
    hx-swap="outerHTML"
>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Name *</span>
            {% if 'name' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['name']|first }}</span>
            {% endif %}
        </div>
        <input
            name="name"
            type="text"
            placeholder="My First Scan"
            class="input input-bordered"
            {% if 'name' in form %}
            value="{{ form.name }}"
            {% endif %}
        />
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Description</span>
            {% if 'description' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['description']|first }}</span>
            {% endif %}
        </div>
        <input
            name="description"
            type="text"
            placeholder="The first scan I ever ran."
            class="input input-bordered"
            {% if 'description' in form %}
            value="{{ form.description }}"
            {% endif %}
        />
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Credentials</span>
            {% if 'credentials' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['credentials']|first }}</span>
            {% endif %}
        </div>
        <textarea
            name="credentials"
            placeholder="list of credentials i.e. root:123456"
            class="textarea textarea-bordered"
        >{% if 'credentials' in form %}{{ form.credentials }}{% endif %}</textarea>
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Configurations</span>
            {% if 'configurations' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['configurations']|first }}</span>
            {% endif %}
        </div>
        <textarea
            name="configurations"
            placeholder="list of configuration names i.e. Audit coverage - thorough"
            class="textarea textarea-bordered"
        >{% if 'configurations' in form %}{{ form.configurations }}{% endif %}</textarea>
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Target URLs *</span>
            {% if 'targets' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['targets']|first }}</span>
            {% endif %}
        </div>
        <textarea
            name="targets"
            placeholder="list of target URLs i.e. https://www.lanmaster53.com"
            class="textarea textarea-bordered"
        >{% if 'targets' in form %}{{ form.targets }}{% endif %}</textarea>
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Scope Inclusions *</span>
            {% if 'scope_includes' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['scope_includes']|first }}</span>
            {% endif %}
        </div>
        <textarea
            name="scope_includes"
            placeholder="list of URLs to include in scope i.e. https://www.lanmaster53.com"
            class="textarea textarea-bordered"
        >{% if 'scope_includes' in form %}{{ form.scope_includes }}{% endif %}</textarea>
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Scope Exclusions</span>
            {% if 'scope_excludes' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['scope_excludes']|first }}</span>
            {% endif %}
        </div>
        <textarea
            name="scope_excludes"
            placeholder="list of URLs to exclude from scope i.e. https://www.lanmaster53.com/do-not-scan"
            class="textarea textarea-bordered"
        >{% if 'scope_excludes' in form %}{{ form.scope_excludes }}{% endif %}</textarea>
    </div>
    <div class="flex flex-col">
        <div class="label">
            <span class="label-text">Node *</span>
            {% if 'node' in errors %}
            <span class="ml-4 text-xs text-red-500">{{ errors['node']|first }}</span>
            {% endif %}
        </div>
        <select
            name="node"
            class="select select-bordered"
        >
        {% for node in nodes %}
            <option
                value="{{ node.id }}"
                {% if 'node' in form and form.node == node.id %}
                selected
                {% endif %}
            >{{ node.name }}</option>
        {% endfor %}
        </select>
    </div>
    <div class="flex flex-row-reverse justify-between mt-9">
        <button id="save" class="btn">Save</button>
        {% if '_other' in errors %}
        <div class="mt-4 ml-4 text-xs text-red-500">{{ errors['_other']|first }}</div>
        {% endif %}
    </div>
</form>