burp_probe/routes/auth.py
from flask import Blueprint, session, request, redirect, url_for, flash, render_template
from burp_probe.decorators import login_required
from burp_probe.models import User
from burp_probe.schemas import login_form_schema

blp = Blueprint('auth', __name__)

@blp.route('/login')
def login():
    if session.get('user_id'):
        return redirect(url_for('core.home'))
    return render_template('pages/login.html')

@blp.route('/login', methods=['POST'])
def login_submit():
    errors = login_form_schema.validate(request.form)
    if errors:
        return render_template(
            'pages/login.html',
            errors=errors,
        ), 400
    user = User.query.filter_by(email=request.form.get('email')).first()
    if user and user.check_password(request.form.get('password')):
        session['user_id'] = user.id
        return redirect(url_for('core.home'))
    flash('Invalid email or password.', category='error')
    return render_template('pages/login.html')

@blp.route('/logout')
@login_required
def logout():
    session.pop('user_id', None)
    session.clear()
    return redirect(url_for('core.index'))

burp_probe/routes/core.py
from flask import Blueprint, current_app, request, redirect, url_for, flash, render_template, abort
from burp_probe import db
from burp_probe.constants import ScanStates
from burp_probe.decorators import hx_trigger, login_required
from burp_probe.helpers import render_partial
from burp_probe.middleware import load_user, strip_empty_params, modify_response
from burp_probe.models import Node, Scan
from burp_probe.services.burp import BurpProApi, BurpScanBuilder, BurpServiceException, BurpIssueParser
from burp_probe.schemas import node_form_create_schema, node_form_update_schema, scan_form_schema
import json
import traceback

blp = Blueprint('core', __name__)

@blp.before_app_request
def call_request_middleware():
    load_user()
    strip_empty_params()

@blp.after_app_request
def call_response_middleware(response):
    response = modify_response(response)
    return response

@blp.route('/')
def index():
    return redirect(url_for('core.home'))

@blp.route('/home')
@login_required
def home():
    return redirect(url_for('core.scans'))

@blp.route('/logo')
def logo():
    return render_template(
        'pages/logo.html',
    )

# region assets

@blp.route('/assets')
@login_required
def assets():
    return render_template(
        'pages/assets.html',
        assets=Scan.get_assets(),
    )

@blp.route('/assets/table')
@login_required
def assets_table():
    return render_partial(
        'partials/tables/assets.html',
        assets=Scan.get_assets(),
    )

# endregion

# region nodes

@blp.route('/nodes')
@login_required
def nodes():
    return render_template(
        'pages/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/table')
@login_required
def nodes_table():
    return render_partial(
        'partials/tables/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/form')
@login_required
def nodes_form():
    form = {}
    if node_id := request.args.get('node_id'):
        if node := Node.query.get(node_id):
            form = node.serialize()
    return render_partial(
        'partials/forms/nodes.html',
        errors={},
        form=form,
    )

@blp.route('/nodes', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_create():
    errors = node_form_create_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node(
        name=request.form.get('name'),
        description=request.form.get('description'),
        protocol=request.form.get('protocol'),
        hostname=request.form.get('hostname'),
        port=request.form.get('port'),
        api_key=request.form.get('api_key'),
    )
    db.session.add(node)
    db.session.commit()
    flash('Node created.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['PATCH'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_update(node_id):
    request.form['id'] = node_id
    errors = node_form_update_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node.query.get(node_id)
    node.name=request.form.get('name')
    node.description=request.form.get('description')
    node.protocol=request.form.get('protocol')
    node.hostname=request.form.get('hostname')
    node.port=request.form.get('port')
    node.api_key=request.form.get('api_key')
    db.session.commit()
    flash('Node updated.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_delete(node_id):
    if not (node := Node.query.get(node_id)):
        abort(404, description='Node does not exist.')
    if node.scans:
        abort(409, description='Node has associated scans')
    db.session.delete(node)
    db.session.commit()
    flash('Node deleted.', 'success')
    return '', 200

@blp.route('/nodes/<string:node_id>/test')
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_test(node_id):
    node = Node.query.get(node_id)
    if node.is_alive:
        flash('Node is available.', 'success')
    else:
        flash('Node is not available.', 'warning')
    return '', 200

# endregion

# region scans

@blp.route('/scans')
@login_required
def scans():
    return render_template(
        'pages/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/table')
@login_required
def scans_table():
    return render_partial(
        'partials/tables/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/form')
@login_required
def scans_form():
    return render_partial(
        'partials/forms/scans.html',
        nodes=Node.get_live_nodes(),
        errors={},
        form={},
    )

@blp.route('/scans', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_create():
    errors = scan_form_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors=errors,
            form=request.form,
        ), 400
    name = request.form.get('name')
    description = request.form.get('description')
    credentials = request.form.get('credentials')
    configurations = request.form.get('configurations')
    scope_includes = request.form.get('scope_includes')
    scope_excludes = request.form.get('scope_excludes')
    target_urls = request.form.get('targets')
    node_id = request.form.get('node')
    node = Node.query.get(node_id)
    # build and run the scan
    scan = Scan(
        name=name,
        description=description,
        status='created',
        node=node,
    )
    db.session.add(scan)
    db.session.flush()
    callback_url = None
    scan_builder = BurpScanBuilder(callback_url, credentials, configurations, scope_includes, scope_excludes, target_urls)
    scan_config = scan_builder.config_as_json
    current_app.logger.debug(f"Scanner Config:\n{json.dumps(scan_config, indent=4)}")
    burp = BurpProApi(
        protocol=node.protocol,
        hostname=node.hostname,
        port=node.port,
        api_key=node.api_key,
    )
    try:
        response = burp.post_scan_config(scan_config)
    except BurpServiceException as e:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors={'_other': [str(e)]},
            form=request.form,
        ), 400
    scan.configuration = json.dumps(scan_config)
    scan.status = ScanStates.STARTED
    scan.task_id = response['task_id']
    db.session.commit()
    flash('Scan initialized.', 'success')
    return '', 201

# endregion

# region scan

@blp.route('/scans/<string:scan_id>')
@login_required
def scan(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_template(
        'pages/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>/header')
@login_required
def scan_header(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_partial(
        'partials/headers/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_delete(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    db.session.delete(scan)
    db.session.commit()
    flash('Scan deleted.', 'success')
    return '', 200

# endregion

# region issues

@blp.route('/scans/<string:scan_id>/issues/table')
@login_required
def issues_table(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    type_ids = [int(t) for t in request.args.get('type_ids', '').split(',') if t]
    return render_partial(
        'partials/tables/issues.html',
        scan=scan,
        type_ids=type_ids,
    )

# endregion

# region issue

@blp.route('/scans/<string:scan_id>/issues/<string:issue_id>')
@login_required
def issue(scan_id, issue_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    if not (issue_event := scan.get_issue_by_id(issue_id)):
        abort(404, description='Issue does not exist.')
    issue_event['parsed'] = BurpIssueParser(issue_event)
    return render_template(
        'pages/issue.html',
        issue_event=issue_event,
    )

# endregion

# region error handlers

from werkzeug.exceptions import HTTPException

@blp.app_errorhandler(HTTPException)
def error_handler(e):
    if 'HX-Request' in request.headers:
        message = e.description
        flash(message, 'error')
        return '', e.code
    else:
        return e

@blp.app_errorhandler(Exception)
def internal_server_error(e):
    if 'HX-Request' in request.headers:
        current_app.logger.error(traceback.format_exc())
        message = 'Internal server error.'
        flash(message, 'error')
        return '', 500
    else:
        return e

# endregion

burp_probe/templates/shared/head.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="htmx-config" content='{"includeIndicatorStyles": false}' />
    <title>Burp Probe</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!--link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daisyui@latest/dist/full.min.css" /-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/daisyui.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/burp-probe.css') }}" />
    <!--script src="https://cdn.tailwindcss.com"></script-->
    <script src="{{ url_for('static', filename='js/tailwind.min.js') }}"></script>
    <!--script src="https://unpkg.com/htmx.org@next/dist/htmx.min.js"></script-->
    <script src="{{ url_for('static', filename='js/htmx.min.js') }}"></script>
    <!--script src="https://unpkg.com/htmx.org@latest/dist/ext/debug.js"></script-->
    <!--script src="{{ url_for('static', filename='js/htmx-debug.js') }}"></script-->
    <script src="{{ url_for('static', filename='js/burp-probe.js') }}"></script>
</head>

burp_probe/templates/shared/layout.html
<!DOCTYPE html>
<html lang="en" data-theme="light" class="bg-base-100 tracking-wide" style="font-family: Roboto, Helvetica, Arial, sans-serif;">
    {% include 'shared/head.html' %}
    <body>
        {{ render_partial('partials/flash.html') }}
        {% block body %}{% endblock %}
    </body>
</html>

burp_probe/templates/shared/page.html
{% extends 'shared/layout.html' %}
{% block body %}
<header class="shadow-lg bg-base-100 relative z-40" style="border-bottom: 3px solid #00b5ef;"><!-- relative prevents content from overlapping header shadow -->
    <nav class="navbar">
        <div class="flex-1">
            <a href="{{ url_for('core.home') }}">
                <img class="max-h-12" src="{{ url_for('static', filename='images/logo.png') }}" />
            </a>
        </div>
        <div class="flex-none">
            <div class="dropdown dropdown-end md:hidden">
                <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path></svg>
                </div>
                <ul class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-lg">
                    <li>
                        <div class="flex items-center justify-end">
                            <a href="{{ url_for('core.assets') }}">Assets</a>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9.004 9.004 0 0 0 8.716-6.747M12 21a9.004 9.004 0 0 1-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 0 1 7.843 4.582M12 3a8.997 8.997 0 0 0-7.843 4.582m15.686 0A11.953 11.953 0 0 1 12 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0 1 21 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0 1 12 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 0 1 3 12c0-1.605.42-3.113 1.157-4.418" />
                            </svg>
                        </div class="flex items-center justify-end">
                    </li>
                    <li>
                        <div>
                            <a href="{{ url_for('core.nodes') }}">Nodes</a>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M7.217 10.907a2.25 2.25 0 1 0 0 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186 9.566-5.314m-9.566 7.5 9.566 5.314m0 0a2.25 2.25 0 1 0 3.935 2.186 2.25 2.25 0 0 0-3.935-2.186Zm0-12.814a2.25 2.25 0 1 0 3.933-2.185 2.25 2.25 0 0 0-3.933 2.185Z" />
                            </svg>
                        </div>
                    </li>
                    <li>
                        <div class="flex items-center justify-end">
                            <a href="{{ url_for('core.scans') }}">Scans</a>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 12.75c1.148 0 2.278.08 3.383.237 1.037.146 1.866.966 1.866 2.013 0 3.728-2.35 6.75-5.25 6.75S6.75 18.728 6.75 15c0-1.046.83-1.867 1.866-2.013A24.204 24.204 0 0 1 12 12.75Zm0 0c2.883 0 5.647.508 8.207 1.44a23.91 23.91 0 0 1-1.152 6.06M12 12.75c-2.883 0-5.647.508-8.208 1.44.125 2.104.52 4.136 1.153 6.06M12 12.75a2.25 2.25 0 0 0 2.248-2.354M12 12.75a2.25 2.25 0 0 1-2.248-2.354M12 8.25c.995 0 1.971-.08 2.922-.236.403-.066.74-.358.795-.762a3.778 3.778 0 0 0-.399-2.25M12 8.25c-.995 0-1.97-.08-2.922-.236-.402-.066-.74-.358-.795-.762a3.734 3.734 0 0 1 .4-2.253M12 8.25a2.25 2.25 0 0 0-2.248 2.146M12 8.25a2.25 2.25 0 0 1 2.248 2.146M8.683 5a6.032 6.032 0 0 1-1.155-1.002c.07-.63.27-1.222.574-1.747m.581 2.749A3.75 3.75 0 0 1 15.318 5m0 0c.427-.283.815-.62 1.155-.999a4.471 4.471 0 0 0-.575-1.752M4.921 6a24.048 24.048 0 0 0-.392 3.314c1.668.546 3.416.914 5.223 1.082M19.08 6c.205 1.08.337 2.187.392 3.314a23.882 23.882 0 0 1-5.223 1.082" />
                            </svg>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="hidden md:inline-block">
                <ul class="menu menu-horizontal px-1">
                    <li>
                        <div class="flex items-center justify-end">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9.004 9.004 0 0 0 8.716-6.747M12 21a9.004 9.004 0 0 1-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 0 1 7.843 4.582M12 3a8.997 8.997 0 0 0-7.843 4.582m15.686 0A11.953 11.953 0 0 1 12 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0 1 21 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0 1 12 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 0 1 3 12c0-1.605.42-3.113 1.157-4.418" />
                            </svg>
                            <a href="{{ url_for('core.assets') }}">Assets</a>
                        </div class="flex items-center justify-end">
                    </li>
                    <li>
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M7.217 10.907a2.25 2.25 0 1 0 0 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186 9.566-5.314m-9.566 7.5 9.566 5.314m0 0a2.25 2.25 0 1 0 3.935 2.186 2.25 2.25 0 0 0-3.935-2.186Zm0-12.814a2.25 2.25 0 1 0 3.933-2.185 2.25 2.25 0 0 0-3.933 2.185Z" />
                            </svg>
                            <a href="{{ url_for('core.nodes') }}">Nodes</a>
                        </div>
                    </li>
                    <li>
                        <div class="flex items-center justify-end">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 12.75c1.148 0 2.278.08 3.383.237 1.037.146 1.866.966 1.866 2.013 0 3.728-2.35 6.75-5.25 6.75S6.75 18.728 6.75 15c0-1.046.83-1.867 1.866-2.013A24.204 24.204 0 0 1 12 12.75Zm0 0c2.883 0 5.647.508 8.207 1.44a23.91 23.91 0 0 1-1.152 6.06M12 12.75c-2.883 0-5.647.508-8.208 1.44.125 2.104.52 4.136 1.153 6.06M12 12.75a2.25 2.25 0 0 0 2.248-2.354M12 12.75a2.25 2.25 0 0 1-2.248-2.354M12 8.25c.995 0 1.971-.08 2.922-.236.403-.066.74-.358.795-.762a3.778 3.778 0 0 0-.399-2.25M12 8.25c-.995 0-1.97-.08-2.922-.236-.402-.066-.74-.358-.795-.762a3.734 3.734 0 0 1 .4-2.253M12 8.25a2.25 2.25 0 0 0-2.248 2.146M12 8.25a2.25 2.25 0 0 1 2.248 2.146M8.683 5a6.032 6.032 0 0 1-1.155-1.002c.07-.63.27-1.222.574-1.747m.581 2.749A3.75 3.75 0 0 1 15.318 5m0 0c.427-.283.815-.62 1.155-.999a4.471 4.471 0 0 0-.575-1.752M4.921 6a24.048 24.048 0 0 0-.392 3.314c1.668.546 3.416.914 5.223 1.082M19.08 6c.205 1.08.337 2.187.392 3.314a23.882 23.882 0 0 1-5.223 1.082" />
                            </svg>
                            <a href="{{ url_for('core.scans') }}">Scans</a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="dropdown dropdown-end">
                <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
                    <div style="background-color: #00b5ef;" class="flex flex-col items-center justify-center leading-10 text-3xl font-light text-white w-10 rounded-full">
                        {{ g.user.name[0] }}
                    </div>
                </div>
                <ul class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-lg">
                    <li>
                        <div class="flex items-center justify-end">
                            <a href="{{ url_for('auth.logout') }}">Logout</a>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15m3 0 3-3m0 0-3-3m3 3H9" />
                            </svg>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<section class="p-4 h-screen flex flex-col">
    {% block content %}{% endblock %}
</section>
<footer></footer>
{% endblock %}