burp_probe/routes/core.py
from flask import Blueprint, current_app, request, redirect, url_for, flash, render_template, abort
from burp_probe import db
from burp_probe.constants import ScanStates
from burp_probe.decorators import hx_trigger, login_required
from burp_probe.helpers import render_partial
from burp_probe.middleware import load_user, strip_empty_params, modify_response
from burp_probe.models import Node, Scan
from burp_probe.services.burp import BurpProApi, BurpScanBuilder, BurpServiceException, BurpIssueParser
from burp_probe.schemas import node_form_create_schema, node_form_update_schema, scan_form_schema
import json
import traceback

blp = Blueprint('core', __name__)

@blp.before_app_request
def call_request_middleware():
    load_user()
    strip_empty_params()

@blp.after_app_request
def call_response_middleware(response):
    response = modify_response(response)
    return response

@blp.route('/')
def index():
    return redirect(url_for('core.home'))

@blp.route('/home')
@login_required
def home():
    return redirect(url_for('core.scans'))

@blp.route('/logo')
def logo():
    return render_template(
        'pages/logo.html',
    )

# region assets

@blp.route('/assets')
@login_required
def assets():
    return render_template(
        'pages/assets.html',
        assets=Scan.get_assets(),
    )

@blp.route('/assets/table')
@login_required
def assets_table():
    return render_partial(
        'partials/tables/assets.html',
        assets=Scan.get_assets(),
    )

# endregion

# region nodes

@blp.route('/nodes')
@login_required
def nodes():
    return render_template(
        'pages/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/table')
@login_required
def nodes_table():
    return render_partial(
        'partials/tables/nodes.html',
        nodes=Node.query.all(),
    )

@blp.route('/nodes/form')
@login_required
def nodes_form():
    form = {}
    if node_id := request.args.get('node_id'):
        if node := Node.query.get(node_id):
            form = node.serialize()
    return render_partial(
        'partials/forms/nodes.html',
        errors={},
        form=form,
    )

@blp.route('/nodes', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_create():
    errors = node_form_create_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node(
        name=request.form.get('name'),
        description=request.form.get('description'),
        protocol=request.form.get('protocol'),
        hostname=request.form.get('hostname'),
        port=request.form.get('port'),
        api_key=request.form.get('api_key'),
    )
    db.session.add(node)
    db.session.commit()
    flash('Node created.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['PATCH'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_update(node_id):
    request.form['id'] = node_id
    errors = node_form_update_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/nodes.html',
            errors=errors,
            form=request.form,
        ), 400
    node = Node.query.get(node_id)
    node.name=request.form.get('name')
    node.description=request.form.get('description')
    node.protocol=request.form.get('protocol')
    node.hostname=request.form.get('hostname')
    node.port=request.form.get('port')
    node.api_key=request.form.get('api_key')
    db.session.commit()
    flash('Node updated.', 'success')
    return '', 201

@blp.route('/nodes/<string:node_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_delete(node_id):
    if not (node := Node.query.get(node_id)):
        abort(404, description='Node does not exist.')
    if node.scans:
        abort(409, description='Node has associated scans')
    db.session.delete(node)
    db.session.commit()
    flash('Node deleted.', 'success')
    return '', 200

@blp.route('/nodes/<string:node_id>/test')
@login_required
@hx_trigger('watch-refresh-nodes')
def nodes_test(node_id):
    node = Node.query.get(node_id)
    if node.is_alive:
        flash('Node is available.', 'success')
    else:
        flash('Node is not available.', 'warning')
    return '', 200

# endregion

# region scans

@blp.route('/scans')
@login_required
def scans():
    return render_template(
        'pages/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/table')
@login_required
def scans_table():
    return render_partial(
        'partials/tables/scans.html',
        scans=Scan.query.all(),
    )

@blp.route('/scans/form')
@login_required
def scans_form():
    return render_partial(
        'partials/forms/scans.html',
        nodes=Node.get_live_nodes(),
        errors={},
        form={},
    )

@blp.route('/scans', methods=['POST'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_create():
    errors = scan_form_schema.validate(request.form)
    if errors:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors=errors,
            form=request.form,
        ), 400
    name = request.form.get('name')
    description = request.form.get('description')
    credentials = request.form.get('credentials')
    configurations = request.form.get('configurations')
    scope_includes = request.form.get('scope_includes')
    scope_excludes = request.form.get('scope_excludes')
    target_urls = request.form.get('targets')
    node_id = request.form.get('node')
    node = Node.query.get(node_id)
    # build and run the scan
    scan = Scan(
        name=name,
        description=description,
        status='created',
        node=node,
    )
    db.session.add(scan)
    db.session.flush()
    callback_url = None
    scan_builder = BurpScanBuilder(callback_url, credentials, configurations, scope_includes, scope_excludes, target_urls)
    scan_config = scan_builder.config_as_json
    current_app.logger.debug(f"Scanner Config:\n{json.dumps(scan_config, indent=4)}")
    burp = BurpProApi(
        protocol=node.protocol,
        hostname=node.hostname,
        port=node.port,
        api_key=node.api_key,
    )
    try:
        response = burp.post_scan_config(scan_config)
    except BurpServiceException as e:
        return render_partial(
            'partials/forms/scans.html',
            nodes=Node.get_live_nodes(),
            errors={'_other': [str(e)]},
            form=request.form,
        ), 400
    scan.configuration = json.dumps(scan_config)
    scan.status = ScanStates.STARTED
    scan.task_id = response['task_id']
    db.session.commit()
    flash('Scan initialized.', 'success')
    return '', 201

# endregion

# region scan

@blp.route('/scans/<string:scan_id>')
@login_required
def scan(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_template(
        'pages/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>/header')
@login_required
def scan_header(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    return render_partial(
        'partials/headers/scan.html',
        scan=scan,
    )

@blp.route('/scans/<string:scan_id>', methods=['DELETE'])
@login_required
@hx_trigger('watch-refresh-scans')
def scans_delete(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    db.session.delete(scan)
    db.session.commit()
    flash('Scan deleted.', 'success')
    return '', 200

# endregion

# region issues

@blp.route('/scans/<string:scan_id>/issues/table')
@login_required
def issues_table(scan_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    type_ids = [int(t) for t in request.args.get('type_ids', '').split(',') if t]
    return render_partial(
        'partials/tables/issues.html',
        scan=scan,
        type_ids=type_ids,
    )

# endregion

# region issue

@blp.route('/scans/<string:scan_id>/issues/<string:issue_id>')
@login_required
def issue(scan_id, issue_id):
    if not (scan := Scan.query.get(scan_id)):
        abort(404, description='Scan does not exist.')
    if not (issue_event := scan.get_issue_by_id(issue_id)):
        abort(404, description='Issue does not exist.')
    issue_event['parsed'] = BurpIssueParser(issue_event)
    return render_template(
        'pages/issue.html',
        issue_event=issue_event,
    )

# endregion

# region error handlers

from werkzeug.exceptions import HTTPException

@blp.app_errorhandler(HTTPException)
def error_handler(e):
    if 'HX-Request' in request.headers:
        message = e.description
        flash(message, 'error')
        return '', e.code
    else:
        return e

@blp.app_errorhandler(Exception)
def internal_server_error(e):
    if 'HX-Request' in request.headers:
        current_app.logger.error(traceback.format_exc())
        message = 'Internal server error.'
        flash(message, 'error')
        return '', 500
    else:
        return e

# endregion

burp_probe/templates/partials/tables/assets.html
<table class="table">
    <thead>
        <tr>
            <th>URL</th>
            <th>Scans</th>
            <th class="text-right"></th>
        </tr>
    </thead>
    <tbody>
    {% if assets|length > 0 %}
    {% for asset in assets %}
        <tr>
            <td><code>{{ asset.url }}</code></td>
            <td>{{ asset.count }}</td>
            <td>
                <div class="flex justify-end"></div>
            </td>
        </tr>
    {% endfor %}
    {% else %}
        <tr>
            <td class="text-center" colspan="4">No assets found.</td>
        </tr>
    {% endif %}
    </tbody>
</table>

burp_probe/templates/partials/tables/issues.html
{% from 'shared/macros.html' import severity_pill %}
<table class="table">
    <thead>
        <tr>
            <th>Name/Resource</th>
            <th>Severity</th>
            <th>Confidence</th>
        </tr>
    </thead>
    <tbody>
    {% if scan.parsed.issue_count > 0 %}
    {% for issue_type in scan.parsed.organized_issue_events %}
        {% set issue_event=issue_type.issue_events[0] %}
        <tr
            class="cursor-pointer hover:bg-gray-100"
            onclick="toggleCollapse('{{ issue_event.issue.type_index }}')"
        >
            <td>
                <div class="flex items-center gap-2">
                    <svg
                        class="w-3 h-3 bp-arrow-closed {% if issue_event.issue.type_index in type_ids %}bp-arrow-opened{% endif %}"
                        data-type="{{ issue_event.issue.type_index }}"
                        xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="3" stroke="currentColor"
                    >
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>
                    <span>{{ issue_event.issue.name }}</span>
                    <span class="min-w-7 px-2 rounded-full text-center text-xs bg-gray-200">{{ issue_type.issue_events|length }}</span>
                </div>
            </td>
            <td>
                <div class="flex items-center">
                    {{ severity_pill(issue_event.issue.severity) }}
                </div>
            </td>
            <td>{{ issue_event.issue.confidence|capitalize }}</td>
        </tr>
    {% for issue_event in issue_type.issue_events %}
        <tr
            class="cursor-pointer hover:bg-gray-100 {% if issue_event.issue.type_index not in type_ids %}bp-collapsed{% endif %}"
            data-type="{{ issue_event.issue.type_index }}"
            onclick="window.location.href='{{ url_for('core.issue', scan_id=scan.id, issue_id=issue_event.id) }}'"
        >
            <td class="pl-16">{{ issue_event.issue.origin }}{{ issue_event.issue.path }}</td>
            <td>
                <div class="flex items-center">
                    {{ severity_pill(issue_event.issue.severity) }}
                </div>
            </td>
            <td>{{ issue_event.issue.confidence|capitalize }}</td>
        </tr>
    {% endfor %}
    {% endfor %}
    {% else %}
        <tr>
            <td class="text-center" colspan="3">No Issues found.</td>
        </tr>
    {% endif %}
    </tbody>
</table>

burp_probe/templates/partials/tables/nodes.html
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Protocol</th>
            <th>Hostname/IP</th>
            <th>Port</th>
            <th>Available</th>
            <th>Active Scans</th>
            <th class="text-right">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% if nodes|length > 0 %}
    {% for node in nodes %}
        <tr>
            <td>{{ node.name }}</td>
            <td><code>{{ node.protocol }}</code></td>
            <td><code>{{ node.hostname }}</code></td>
            <td><code>{{ node.port }}</code></td>
            <td>
                <div class="flex items-center">
                    <button
                        hx-get="{{ url_for('core.nodes_test', node_id=node.id) }}"
                        hx-trigger="click"
                        hx-swap="none"
                    >
                    {% if node.is_alive %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="green" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>
                    {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="red" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>
                    {% endif %}
                    </button>
                </div>
            </td>
            <td>{{ node.active_scans|length }}</td>
            <td>
                <div class="flex items-center justify-end">
                    <button
                        hx-get="{{ url_for('core.nodes_form') }}"
                        hx-target="#form_container"
                        hx-vals='{"node_id": "{{ node.id }}"}'
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                        </svg>
                    </button>
                    <button
                        class="ml-2"
                        hx-delete="{{ url_for('core.nodes_delete', node_id=node.id) }}"
                        hx-trigger="click"
                        hx-swap="none"
                        hx-confirm="Are you sure you want to delete node {{ node.url }}?"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                        </svg>
                    </button>
                </div>
            </td>
        </tr>
    {% endfor %}
    {% else %}
        <tr>
            <td class="text-center" colspan="7">No nodes found. Click "+" to add one.</td>
        </tr>
    {% endif %}
    </tbody>
</table>

burp_probe/templates/partials/tables/scans.html
{% from 'shared/macros.html' import status_svg %}
<table class="table">
    <thead>
        <tr>
            <th>Start Time</th>
            <th>Name</th>
            <th>Issues</th>
            <th>Node</th>
            <th>Status</th>
            <th class="text-right">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% if scans|length > 0 %}
    {% for scan in scans %}
        <tr
            class="cursor-pointer hover:bg-gray-100"
            onclick="window.location.href='{{ url_for('core.scan', scan_id=scan.id) }}'"
        >
            <td>{{ scan.parsed.start_time|capitalize }}</td>
            <td>{{ scan.name }}</td>
            <td>
                <div class="flex items-center gap-2">
                    <span class="min-w-7 px-2 rounded-full text-center text-xs text-white bg-red-500">{{ scan.parsed.issues_by_severity.high|length }}</span>
                    <span class="min-w-7 px-2 rounded-full text-center text-xs text-white bg-orange-500">{{ scan.parsed.issues_by_severity.medium|length }}</span>
                    <span class="min-w-7 px-2 rounded-full text-center text-xs text-white bg-blue-500">{{ scan.parsed.issues_by_severity.low|length }}</span>
                    <span class="min-w-7 px-2 rounded-full text-center text-xs text-white bg-gray-500">{{ scan.parsed.issues_by_severity.info|length }}</span>
                </div>
            </td>
            <td>{{ scan.node.name }}</td>
            <td>
                <div class="flex items-center gap-2">
                    {{ status_svg(scan) }}
                    <span>{{ scan.status|capitalize }}</span>
                </div>
            </td>
            <td>
                <div class="flex items-center justify-end">
                    <button
                        hx-delete="{{ url_for('core.scans_delete', scan_id=scan.id) }}"
                        hx-trigger="click consume"
                        hx-swap="none"
                        hx-confirm="Are you sure you want to delete scan {{ scan.name }}?"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                        </svg>
                    </button>
                </div>
            </td>
        </tr>
    {% endfor %}
    {% else %}
        <tr>
            <td class="text-center" colspan="6">No scans found. Click "+" to add one.</td>
        </tr>
    {% endif %}
    </tbody>
</table>